name: DockerCI

on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        docker build . -t nihalwasim/mock-http-server:latest
    - name: Publish
      run: |
        docker push nihalwasim/mock-http-server:latest

